[package]
name = "Efiil Test"
description = "Efiil Testing"
homepage = "https://www.nexusmods.com/morrowind/mods/*****"
repository = "https://github.com/longod/MWSE-Effil"
authors = ["longod"]
version = "1.0.0"

[dependencies]
assets = [
    "MWSE/mods/effil_test",
]

[dependencies."Efiil"]
mwse-module = "effil"

[dependencies.mwse]
buildnumber = 3786
