name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
      # https://github.com/marketplace/actions/enable-developer-command-prompt
    - uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x86
    - name: Build Lua
      working-directory: ${{github.workspace}}/src/MWSE/deps/LuaJIT/src
      run: ./msvcbuild.bat

    - name: Build Effil
      working-directory: ${{github.workspace}}/src/effil
      run: |
        cmake . -A Win32 -DLUA_INCLUDE_DIR="${{github.workspace}}/src/MWSE/deps/LuaJIT/src" -DLUA_LIBRARY="${{github.workspace}}/src/MWSE/deps/LuaJIT/src/lua*.lib"
        cmake --build . --target effil --config Release -- -m
